In [1]:
import numpy as np

In [14]:
plaintext = "nhom jong tv siemreap"
plaintext

'nhom jong tv siemreap'

In [17]:
plaintext = plaintext.replace(" ", "").lower()
plaintext

'nhomjongtvsiemreap'

In [33]:
key = 'test'

In [22]:
chr(97)

'a'

In [23]:
ord('a')

97

In [24]:
map_letter = {chr(i):i-97 for i in range(97,97+26)}
map_letter

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [25]:
map_letter_rev = {i-97:chr(i) for i in range(97,97+26)}
map_letter_rev

{0: 'a',
 1: 'b',
 2: 'c',
 3: 'd',
 4: 'e',
 5: 'f',
 6: 'g',
 7: 'h',
 8: 'i',
 9: 'j',
 10: 'k',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o',
 15: 'p',
 16: 'q',
 17: 'r',
 18: 's',
 19: 't',
 20: 'u',
 21: 'v',
 22: 'w',
 23: 'x',
 24: 'y',
 25: 'z'}

In [26]:
toNumber = [map_letter[i] for i in plaintext]
toNumber

[13, 7, 14, 12, 9, 14, 13, 6, 19, 21, 18, 8, 4, 12, 17, 4, 0, 15]

In [27]:
keyToNumber = [map_letter[i] for i in key]
keyToNumber

[19, 4, 18, 19]

In [29]:
block_length = len(plaintext)// 2
block_length

9

In [34]:
lengthOfN = int(pow(len(key),0.5))
lengthOfN

2

In [40]:
key_matrix = np.array(keyToNumber).reshape((lengthOfN, lengthOfN))
key_matrix

array([[19,  4],
       [18, 19]])

In [45]:
plaintext_array = np.array(toNumber)
plaintext_array

array([13,  7, 14, 12,  9, 14, 13,  6, 19, 21, 18,  8,  4, 12, 17,  4,  0,
       15])

In [49]:
plaintextBlock = np.split(plaintext_array, block_length)

In [50]:
plaintextBlock

[array([13,  7]),
 array([14, 12]),
 array([ 9, 14]),
 array([13,  6]),
 array([19, 21]),
 array([18,  8]),
 array([ 4, 12]),
 array([17,  4]),
 array([ 0, 15])]

In [51]:
plaintextBlock[0]

array([13,  7])

In [54]:
np.matmul(plaintextBlock[0],key_matrix) % 26

array([9, 3])

In [55]:
ciphertext_block = [np.matmul(plaintextBlock[i],key_matrix) % 26 for i in range(len(plaintextBlock))]
ciphertext_block

[array([9, 3]),
 array([14, 24]),
 array([ 7, 16]),
 array([17, 10]),
 array([11,  7]),
 array([18, 16]),
 array([ 6, 10]),
 array([ 5, 14]),
 array([10, 25])]

In [56]:
ciphertext_array = np.concatenate(ciphertext_block)

In [57]:
ciphertext_array

array([ 9,  3, 14, 24,  7, 16, 17, 10, 11,  7, 18, 16,  6, 10,  5, 14, 10,
       25])

In [61]:
ciphertext = [map_letter_rev[ciphertext_array[i]] for i in range(len(ciphertext_array))]
ciphertext

['j',
 'd',
 'o',
 'y',
 'h',
 'q',
 'r',
 'k',
 'l',
 'h',
 's',
 'q',
 'g',
 'k',
 'f',
 'o',
 'k',
 'z']

In [62]:
''.join(ciphertext)

'jdoyhqrklhsqgkfokz'

In [63]:
np.linalg.inv(key_matrix)

array([[ 0.06574394, -0.01384083],
       [-0.06228374,  0.06574394]])

In [64]:
np.linalg.det(key_matrix)

289.00000000000006

In [65]:
round(np.linalg.det(key_matrix))

289

In [94]:
adj_key_matrix = np.linalg.inv(key_matrix) * round(np.linalg.det(key_matrix))
np.round(adj_key_matrix)

array([[ 19.,  -4.],
       [-18.,  19.]])

In [95]:
pow(289,-1,26)

9

In [96]:
pow(3,-1,26)

9

In [104]:
key_inverse = (9 * adj_key_matrix) % 26
np.round(key_inverse)

array([[15., 16.],
       [20., 15.]])

In [105]:
ciphertext_number = [map_letter[i] for i in ciphertext]
ciphertext_number

[9, 3, 14, 24, 7, 16, 17, 10, 11, 7, 18, 16, 6, 10, 5, 14, 10, 25]

In [106]:
ciphertext_array = np.array(ciphertext_number)
ciphertext_array

array([ 9,  3, 14, 24,  7, 16, 17, 10, 11,  7, 18, 16,  6, 10,  5, 14, 10,
       25])

In [107]:
ciphertext_block = np.split(ciphertext_array, block_length)
ciphertext_block

[array([9, 3]),
 array([14, 24]),
 array([ 7, 16]),
 array([17, 10]),
 array([11,  7]),
 array([18, 16]),
 array([ 6, 10]),
 array([ 5, 14]),
 array([10, 25])]

In [111]:
plaintextBlock = [np.round(np.matmul(ciphertext_block[i], key_inverse)).astype(int) % 26 for i in range(len(ciphertext_block))]
plaintextBlock

[array([13,  7]),
 array([14, 12]),
 array([ 9, 14]),
 array([13,  6]),
 array([19, 21]),
 array([18,  8]),
 array([ 4, 12]),
 array([17,  4]),
 array([ 0, 15])]

In [112]:
plaintext_array = np.concatenate(plaintextBlock)

In [113]:
plaintext_array

array([13,  7, 14, 12,  9, 14, 13,  6, 19, 21, 18,  8,  4, 12, 17,  4,  0,
       15])

In [90]:
type(plaintext_array[0])

numpy.float64

In [115]:
plaintext_list = [map_letter_rev[round(i)] for i in plaintext_array]
plaintext_list

['n',
 'h',
 'o',
 'm',
 'j',
 'o',
 'n',
 'g',
 't',
 'v',
 's',
 'i',
 'e',
 'm',
 'r',
 'e',
 'a',
 'p']

In [116]:
''.join(plaintext_list)

'nhomjongtvsiemreap'